# -*- coding: utf-8 -*-
"""Copy of Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMjwwkwSM-YNDDOT67a9kxkJ4NxgP7dB
"""

# E-commerce Sales Performance & Growth Analysis Pipeline

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Sample data

data = {
    "order_id": [1, 2, 3, 4, 5, 6],
    "order_date": [
        "2024-01-05", "2024-01-15",
        "2024-02-10", "2024-02-18",
        "2024-03-12", "2024-03-25"
    ],
    "customer_id": ["C1", "C2", "C1", "C3", "C2", "C4"],
    "product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone", "Laptop"],
    "sales": [200, 300, 400, 500, 600, 700]
}

df = pd.DataFrame(data)
df["order_date"] = pd.to_datetime(df["order_date"])

# Monthly sales analysis

df["month"] = df["order_date"].dt.to_period("M")

monthly_sales = df.groupby("month")["sales"].sum().reset_index()
monthly_sales["month"] = monthly_sales["month"].astype(str)

monthly_sales["mom_growth_%"] = (
    monthly_sales["sales"].pct_change() * 100
).round(2)

monthly_sales["sales_share_%"] = (
    monthly_sales["sales"] / monthly_sales["sales"].sum() * 100
).round(2)

# Function to print table in a box
def print_box(title, df):
    print("+" + "-"*(len(title)+4) + "+")
    print(f"|  {title}  |")
    print("+" + "-"*(len(title)+4) + "+")
    print(df.to_string(index=False))
    print("+" + "-"*(len(title)+4) + "+\n")

print_box("MONTHLY SALES ANALYSIS", monthly_sales)

# Product level analysis

product_analysis = (
    df.groupby("product")
    .agg(
        total_sales=("sales", "sum"),
        average_sales=("sales", "mean"),
        total_orders=("order_id", "count")
    )
    .reset_index()
    .sort_values("total_sales", ascending=False)
)

print_box("PRODUCT LEVEL ANALYSIS", product_analysis)

# Customer level analysis

customer_analysis = (
    df.groupby("customer_id")
    .agg(
        total_spent=("sales", "sum"),
        avg_order_value=("sales", "mean"),
        order_count=("order_id", "count")
    )
    .reset_index()
    .sort_values("total_spent", ascending=False)
)

print_box("CUSTOMER LEVEL ANALYSIS", customer_analysis)

# Visualizations

plt.figure()
sns.barplot(data=monthly_sales, x="month", y="sales")
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

plt.figure()
sns.barplot(data=monthly_sales, x="month", y="mom_growth_%")
plt.title("Month-over-Month Growth")
plt.xlabel("Month")
plt.ylabel("Growth (%)")
plt.show()

plt.figure()
plt.pie(
    monthly_sales["sales"],
    labels=monthly_sales["month"],
    autopct="%1.1f%%",
    startangle=90
)
plt.title("Sales Contribution by Month")
plt.show()

# Calculate key insights
best_month = monthly_sales.loc[monthly_sales['sales'].idxmax()]
top_product = product_analysis.iloc[0]
top_customer = customer_analysis.iloc[0]

print("+" + "-"*30 + "+")
print("| KEY INSIGHTS                |")
print("+" + "-"*30 + "+")
print(f"- Best month: {best_month['month']}")
print(f"- Top product: {top_product['product']}")
print(f"- Top customer: {top_customer['customer_id']}")
print("+" + "-"*30 + "+")

monthly_sales["growth_change"] = monthly_sales["mom_growth_%"].diff()
slowdown = monthly_sales[monthly_sales["growth_change"] < 0]

if not slowdown.empty:
    print("+" + "-"*40 + "+")
    print("| GROWTH SLOWDOWN DETECTED    |")
    print("+" + "-"*40 + "+")
    print(slowdown[["month", "mom_growth_%"]].to_string(index=False))
    print("+" + "-"*40 + "+")